# Generated by Django 4.2.3 on 2023-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=400)),
                ('g_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('work_conditions', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
